blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation
    url: https://github.com/MichaelGrafnetter/DSInternals/tree/master/Documentation/PowerShell
    about: Check the PowerShell cmdlet documentation before opening an issue.
  - name: ğŸ“‹ Changelog
    url: https://github.com/MichaelGrafnetter/DSInternals/blob/master/Documentation/CHANGELOG.md
    about: Review the changelog to see if your issue has been addressed in a recent release.
  - name: ğŸ“ Contributing Guidelines
    url: https://github.com/MichaelGrafnetter/DSInternals/blob/master/.github/CONTRIBUTING.md
    about: Read the contributing guidelines before submitting.
